### ISSUE TITLE
how to use the persistor? 

### ISSUE THREAD

**Issue by zilahir** [robinmalburn/redux-persist-chrome-storage#1]
Hey, 

while i am familiar with `redux-presist` in different react apps, I was wondering how to use this. Where to import the `persistor`? 

Thanks in advance!

**Comment by robinmalburn** [comment]
Hey there,

So, the idea with this is for it to plug in to Chrome's Storage API, so was predominantly designed for things like storing user preferences fro Chrome plugins.  As such, you'd want to import the persistor in the entry points for your options page and, if you have one, the user interface of your plugin to surface those settings into (so, the plugin pop up for example).  Essentially, exactly where you'd be creating or importing your redux store.  That then lets you access all your persisted settings via redux as an abstraction layer on top of Chrome Storage.

One heads up, I wrote this a few years ago and have since switched to using Vue for most of my JS development, so I know React and Redux have likely changed a fair bit overtime - hopefully everything in this little package is still compatible, but I can't really attest to that, so just something to be mindful.

Hope all that helps and hope the you find the package helpful! :)

**Comment by zilahir** [comment]
Hey @robinmalburn 

thank you for the answer! :) it works seamlessly :)
